
import type { ReactNode } from "react";
import type { Metadata } from "next";

import "../Heat_risk/styles/leaflet.css";

import Header from "../../Header/page";
import ChatBot from "./components/ChatBot";
import Foter from "../../Footer/Footer";

export const metadata: Metadata = {
  title: "EcoRisk",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function HeatRiskLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <section className="min-h-screen">
      <Header />
      <ChatBot />
      <main>{children}</main>
      <Foter />
    </section>
  );
}
