/* import type { ReactNode } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../Heat_risk/styles/leaflet.css";
import Header from "./components/Header";
import ChatBot from "./components/ChatBot";
import Foter from "./components/Foter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EcoRisk",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Header />
        <ChatBot />
        {children}
        <Foter />
      </body>
    </html>
  );
}

 */

import type { ReactNode } from "react";
import type { Metadata } from "next";

import "../Heat_risk/styles/leaflet.css";

import Header from "./components/Header";
import ChatBot from "./components/ChatBot";
import Foter from "./components/Foter";

export const metadata: Metadata = {
  title: "EcoRisk",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function HeatRiskLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <section className="min-h-screen">
      <Header />
      <ChatBot />
      <main>{children}</main>
      <Foter />
    </section>
  );
}
